// apiKeys.js
export const apiKeys = [
  "q5VLqNQBZu", // SERVER (DO NOT USE)
  "qRRiRVIda4", // Trevor
  "XHepTGEMKG", // Bros
  "B0ys0DVG7h", // Herm
  "bjY8foyWPS",
  "0zvjD3DACk",
  "oboNCFl3Zu",
  "K9nMPLxCgZ",
  "czCiIsttmz",
  "HLMriYeZlK",
  "9gPUofSvk7",
  "r5B6EpDKz9",
  "zOuKpaMe6O",
  "mtyFSNhmGy",
  "jQtla6BrBl",
  "ND4WLoOsA0",
  "RAwOdRhXkY",
  "7YqWRXpTUj",
  "Z3A1cqHBpn",
  "t5CxVuj5QJ",
  "lKfuxUJke4",
  "SNRBoJbezZ",
  "AULUDk5q6i",
  "nvwIl3vDXf",
  "pl4puKy4d2",
  "ZKzLWFL6vI",
  "Ex4JUalKdz",
  "Q6YWTJs1xm",
  "5EY9wTvFdx",
  "ZCiqSUsAL7",
  "BozRgu8UEY",
  "YGOw2gdiRr",
  "yKmo1vBwAf",
  "xg4J5UdDOF",
  "UwLdSUzwXG",
  "nE1Fa4AxDY",
  "TteIGCVEkB",
  "kC92KCVTsV",
  "1oPZ85czPm",
  "VoiFnwQ7dX",
  "WONrQKOosN",
  "twk0ADDojL",
  "35dpyglWMz",
  "pXPG5sSESn",
  "NoYtjD93n0",
  "9KGGGplY1a",
  "XFUuRecQL5",
  "Ey6rR1LZ8A",
  "e62yDQ0Bsp",
  "8Ei5zPq936",
];
